package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.IOException;

import javax.swing.JOptionPane;
public class accountSelectionController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	public Label usernameLabel;

	// Event Listener on Button.onAction
	@FXML
	public void UserAccountPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("mainWindowAfterSignIn.fxml"));
		root = loader.load();
		mainWindowAfterSignInController MainWindowAfterSignInController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void kidsAccountPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Kids Netflix Coming Soon.");
	}
}
