package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.PasswordField;

public class getStartedStep01_BController implements Initializable{
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private TextField takeEmailStepOne;
	@FXML
	private PasswordField takePasswordStepOne;

	// Event Listener on Button.onAction
	@FXML
	public void signInPressedStepOneB(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("signInUI.fxml"));
		root = loader.load();
		signInUIController SignInUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void nextButtonStepOneB(ActionEvent event)throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep02.fxml"));
		root = loader.load();
		getStartedStep02Controller GetStartedStep02Controller = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		LandingPageUIController landingPageUIController = new LandingPageUIController();
		String setEmail = landingPageUIController.takeEmail;
		takeEmailStepOne.setText(setEmail);
		
	}
}
