package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;

import javax.swing.JOptionPane;

public class getStartedStep03_BController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	public String Name;
	@FXML
	private TextField takeCardNumber;
	@FXML
	private TextField takeExpirationDate;
	@FXML
	private TextField takeCVV;
	@FXML
	private TextField takeNameOnCard;
	
	
	// Event Listener on Button.onAction
	@FXML
	public void startMembershipPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String cardNumber = takeCardNumber.getText();
		String expirationDate = takeExpirationDate.getText();
		String CVV = takeCVV.getText();
		Name = takeNameOnCard.getText();
		if(cardNumber.equals("123ABC")) {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedFinish.fxml"));
			root = loader.load();
			getStartedFinishController GetStartedFinishController = loader.getController();
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.show();
		}
		else {
			JOptionPane.showMessageDialog(null, "Please Enter Correct Details.");
		}
	}
}
