package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;

public class getStartedStep03Controller {
	private Stage stage;
	private Scene scene;
	private Parent root;
	// Event Listener on Button.onAction
	@FXML
	public void CreditOrDebitPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep03_B.fxml"));
		root = loader.load();
		getStartedStep03_BController GetStartedStep03_BController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
