package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;


public class getStartedStep02_MobileController {
	private Stage stage;
	private Scene scene;
	private Parent root;

	// Event Listener on Button.onAction
	@FXML
	public void mobileSelected(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void basicSelected(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep02_Basic.fxml"));
		root = loader.load();
		getStartedStep02_BasicController GetStartedStep02_BasicController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void standardSelected(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep02_Standard.fxml"));
		root = loader.load();
		getStartedStep02_StandardController GetStartedStep02_StandardController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void premiumSelected(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep02_B.fxml"));
		root = loader.load();
		getStartedStep02_BController GetStartedStep02_BController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void nextButtonPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep03.fxml"));
		root = loader.load();
		getStartedStep03Controller GetStartedStep03Controller = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
