package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class getStartedFinishController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	// Event Listener on Button.onAction
	@FXML
	public void continuePressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("accountSelection.fxml"));
		root = loader.load();
		accountSelectionController AccountSelectionController = loader.getController();
		getStartedStep03_BController GetStartedStep03_BController = new getStartedStep03_BController();
		String name = GetStartedStep03_BController.Name;
		AccountSelectionController.usernameLabel.setText(name);
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
