package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

public class getStartedStep01Controller {
	private Stage stage;
	private Scene scene;
	private Parent root;
	// Event Listener on Button.onAction
	@FXML
	public void signInPressedStepOne(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("signInUI.fxml"));
		root = loader.load();
		signInUIController SignInUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void nextPressedStepOne(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep01_B.fxml"));
		root = loader.load();
		getStartedStep01_BController GetStartedStep01_BController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void questionsContactUsStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void FAQStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void privacyStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void helpCenterStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void cookesPreferencesStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void netflixShopStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void corporateInformationStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void termsOfUseStepOne(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
}
