package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class getStartedStep02Controller {
	private Stage stage;
	private Scene scene;
	private Parent root;

	// Event Listener on Button.onAction
	@FXML
	public void signInButtonStep02(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("signInUI.fxml"));
		root = loader.load();
		signInUIController SignInUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void nextButtonStep02(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep02_B.fxml"));
		root = loader.load();
		getStartedStep02_BController GetStartedStep02_BController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
}
