package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.scene.Node;
import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.MenuButton;

public class LandingPageUIController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	
	@FXML
	private TextField takeEmailAddress;
	@FXML
	private TextField takeEmailAddress2;
	@FXML
	private MenuButton menuBarLanguages;
	
	public String takeEmail;

	// Event Listener on Button.onAction
	@FXML
	public void signInPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("signInUI.fxml"));
		root = loader.load();
		signInUIController SignInUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void getStartedPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		takeEmail = takeEmailAddress.getText();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep01.fxml"));
		root = loader.load();
		getStartedStep01Controller GetStartedStep01Controller = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void whatisNetflixPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void getStartedPressed2(ActionEvent event)throws IOException {
		// TODO Autogenerated
		takeEmail = takeEmailAddress2.getText();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("getStartedStep01.fxml"));
		root = loader.load();
		getStartedStep01Controller GetStartedStep01Controller = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void QuestionsContactUsPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact Us: netflix@ZainZameer.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void FAQPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Enjoy each and every series you watch on 4k Ultra");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void investorRelationsPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Business Inquiries: netflix@business.investors.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void privacyPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "All your information is completely encrypted in one on one form.\nSafe & Secure.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void speedTestPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null,"Our servers are at best speed as caused, no worries");
		
	}
	// Event Listener on MenuButton[#menuBarLanguages].onAction
	@FXML
	public void menuBarLanguagesPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void helpcenterPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact us: netflix@helpcenter.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void jobsPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Contact us: netflix@jobs.com");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void CookiePrefrencesPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Encrypted cookies are preffered in our company.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void legalNotices(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Legal Application by US Government.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void AccountPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "First Sign in!");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void waystowatchPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "You can watch on mobile,PC or TV screens.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void cooperateInformationPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Corporate Information mails directly to our company.\nSafe & Secure.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void onlyonNetflixPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "There are series that are only available on netflix.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void mediaCenterPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "Visit our Media Center @US,Los Angelous,128-OO.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void termsofusePressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void contactUsPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void howmuchdoesnetflixcostPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void wherecaniwatchPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void isnetflixgoodforkidsPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void whatcaniwatchonnetflixPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void howdoicancelPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, "It is an application where you can watch your favourite series limitless.");
		
	}
	// Event Listener on Button.onAction
	
}
