package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

public class mainWindowAfterSignInController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	
	// Event Listener on Button.onAction
	@FXML
	public void playPeakyPressed(ActionEvent event) throws IOException {
		// Pop up window
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Peaky Blinders - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		stage.show();
	}
	
	@FXML
	public void watchPeakyTrailer(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Peaky Blinders - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		stage.show();
	}
	
	@FXML
	public void breakingBadPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Breaking Bad - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("breakingBad.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void moneyHeistPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Money Heist - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("moneyHeist.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void strangerThingsPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Stranger Things - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("strangerThings.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void wednesdayPressed(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null,"Coming Soon.");
	}
	// Event Listener on Button.onAction
	@FXML
	public void luciferPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Lucifer - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("lucifer.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void squidGamePressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Squid Game - Season 01");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("squidGame.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void blackVeilPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Black Viel Brides - In The End");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("blackVielBrides.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void ChrisBrownPressed(ActionEvent event)  throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Chris Brown - Indigo");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("indeed.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void atifAslamPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Atif Aslam - Kadi Te Hans (VELO)");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("atif.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void YSPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Young Stunners - Why not meri jaan (PepsiCo)");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("YS.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void NostalgiaPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("Boljani - Lostalgia");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("JANI.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void apDhillonPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("AP Dhillon - Drop Top - Gurinder Grill");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("apDhillon.mp4");
		stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void starboyPressed(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("peakyBlindersMedia.fxml"));
		Parent root1 = (Parent) loader.load();
		Stage stage = new Stage();
		stage.setTitle("The Weekend - Starboy (Audio)");
		stage.setScene(new Scene(root1));
		stage.getIcons().add(new Image(getClass().getResourceAsStream("netflixLogo.png")));
		peakyBlindersMediaController PeakyBlindersMediaController = loader.getController();
		PeakyBlindersMediaController.setMediaFile("starBoy.mp4");
		stage.show();
	}
}
