package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;

import java.io.File;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.util.Duration;

public class peakyBlindersMediaController implements Initializable{
	@FXML
	private MediaView peakyBlindersTV;
	
	private MediaPlayer mediaPlayer;
	
	public File file;
	private Media media;

	// Event Listener on Button.onAction
	@FXML
	public void playPeakyPressed(ActionEvent event) {
		// TODO Autogenerated
		mediaPlayer.play();
	}
	// Event Listener on Button.onAction
	@FXML
	public void pausePeakyPressed(ActionEvent event) {
		// TODO Autogenerated
		mediaPlayer.pause();
	}
	// Event Listener on Button.onAction
	@FXML
	public void resetPeakyPressed(ActionEvent event) {
		// TODO Autogenerated
		if(mediaPlayer.getStatus()!=MediaPlayer.Status.READY) {
			mediaPlayer.seek(Duration.seconds(0.0));
			
		}
		
	}
	public void setMediaFile(String filename) {
        file = new File(filename);
        media = new Media(file.toURI().toString());
        mediaPlayer = new MediaPlayer(media);
        peakyBlindersTV.setMediaPlayer(mediaPlayer);
    }
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		setMediaFile("peakyBlindersTrailer.mp4");
	}
}
