package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.CheckBox;
import javafx.scene.Node;

public class signInUIController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private TextField enterEmailSignInPage;
	@FXML
	private CheckBox rememberMeSelect;
	@FXML
	private PasswordField enterPassSignInPage;

	// Event Listener on Button.onAction
	@FXML
	public void SignInPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String userEmail = enterEmailSignInPage.getText();
		String userPass = enterPassSignInPage.getText();
		if(userEmail.equals("zain@gmail.com") && userPass.equals("123456")) {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("accountSelection.fxml"));
			root = loader.load();
			accountSelectionController AccountSelectionController = loader.getController();
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.show();
		}
		else {
			JOptionPane.showMessageDialog(null,"Email or Password is incorrect");
			enterEmailSignInPage.clear();
			enterPassSignInPage.clear();
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void NeedHelpPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void signUpNowPressedSignInPage(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void QuestionsContactUsPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void FAQPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void cookiePreferencesPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void helpCenterPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void corporateInformationPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void termsOfUsePressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void PrivacyPressed(ActionEvent event) {
		// TODO Autogenerated
	}
}
